# Generated by Django 6.0.3 on 2026-09-04 20:03

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.rename_image, validators=[common.utils.validate_image_size, common.utils.validate_image_extension]),
        ),
    ]
