# Generated by Django 6.0.3 on 2026-04-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='email',
            field=models.EmailField(default='example@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
