# Generated by Django 6.0.3 on 2026-04-12 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_design_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='design',
            unique_together={('user', 'type')},
        ),
        migrations.AddField(
            model_name='design',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/previews/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='type',
            field=models.CharField(choices=[('banner', 'Banner'), ('feature', 'Feature'), ('carousel', 'Carousel')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['user', 'type'], name='designs_des_user_id_667c8e_idx'),
        ),
        migrations.RemoveField(
            model_name='design',
            name='email',
        ),
    ]
