# Generated by Django 6.0.3 on 2026-04-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_alter_design_unique_together_design_preview_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='designs/')),
                ('element_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('banner', 'Banner'), ('feature', 'Feature'), ('carousel', 'Carousel')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.design')),
            ],
        ),
    ]
