# Generated by Django 6.0.3 on 2026-09-04 20:02

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_designimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='designimage',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.rename_image, validators=[common.utils.validate_image_size, common.utils.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='design',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.rename_image, validators=[common.utils.validate_image_size, common.utils.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='designimage',
            name='file',
            field=models.ImageField(upload_to=common.utils.rename_image, validators=[common.utils.validate_image_size, common.utils.validate_image_extension]),
        ),
    ]
