# Generated by Django 6.0.3 on 2026-09-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_designimage_preview_alter_design_preview_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
