# Generated by Django 6.0.3 on 2026-09-06 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_design_is_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='design',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['is_template'], name='designs_des_is_temp_a672f1_idx'),
        ),
    ]
